name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-nuget-package:
    if: |
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') || 
      (github.event_name == 'release' && github.event.release.target_commitish == 'main')
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC (trusted publisher setup)
      contents: read

    steps:
      - name: Publish NuGet package
        uses: vestfoldfylke/shared/.github/actions/nuget-publish@7fb96bbc6fd6e85f89e5fd90c4feee887910bd90 # v1.3.1
        with:
          nuget_user: ${{ secrets.NUGET_USER }}
          dotnet_version: "10.0.x"
          project_release_path: "Vestfold.Extensions.MongoDb/bin/Release"
